### ISSUE TITLE
Code for Neural implicit Reconstruction

### ISSUE THREAD

**Issue by lapatric** [FlyingGiraffe/vnn#3]
Hi

Would it be possible for you to make the code for chapter 5.3 "Neural Implicit Reconstruction" of your paper available.

Many thanks.

**Comment by FlyingGiraffe** [comment]
Hi,

Maybe I can clean up the code and push it to another repo, but it may take a while. Didn't do this before because it has much overlapping to the OccNet code and there were too many redundancies...

Congyue

**Comment by XLechter** [comment]
Hi, @FlyingGiraffe 
I'm also intereted in the completion experiment, and will appreciate it if you could give some example codes about how you regress the occupancy probability using the ResNet decoder.
Thank you so much.

**Comment by FlyingGiraffe** [comment]
Hi,

I've pushed the coder [here](https://github.com/FlyingGiraffe/vnn-neural-implicits). My apology for the procrastination - it's kind of left behind my mind... Thanks again for the suggestions!

Congyue
