### ISSUE TITLE
Implementation of VNMaxPooling

### ISSUE THREAD

**Issue by tranluan** [FlyingGiraffe/vnn#5]
Hi @FlyingGiraffe,
In the maxpooling implementation, at this line: 
https://github.com/FlyingGiraffe/vnn/blob/8e6a45be00c90611311dd4be5d0038ca5d0ee94b/models/vn_layers.py#L141

In order to get the indices `idx`, are we suppose to use `argmax` instead of `max` operation?

**Comment by FlyingGiraffe** [comment]
The output of the `max` function is a tuple of (values, indices) - in some later pytorch versions. If you're using an earlier version it may not return the indices
