### ISSUE TITLE
Where can I get the supplementary material?

### ISSUE THREAD

**Issue by danpeng2** [FlyingGiraffe/vnn#9]
Hi, Thanks for your work. I am very interested in your work and would like to learn more about your experimental results from the supplementary material. Where can I get the supplementary material?

**Comment by FlyingGiraffe** [comment]
Hi, thanks for your interest. In our [arxiv version ](https://arxiv.org/pdf/2104.12229.pdf) we have attached the supplementary material to the end. I can also update the project website to include it, but it may take a while...

Best,
Congyue
